# Generated by Django 4.2.6 on 2023-10-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_forumpost_date_alter_forumpost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
