# Generated by Django 4.2.6 on 2023-10-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_forumpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
