# Generated by Django 4.2.6 on 2023-10-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0004_forumpost_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forumpost",
            name="topic",
            field=models.CharField(default="none", max_length=140),
        ),
    ]
