# Generated by Django 4.2.6 on 2023-10-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_profile_age_profile_bio_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile", name="role", field=models.CharField(max_length=1),
        ),
    ]
