# Generated by Django 4.2.6 on 2023-10-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrow_book", "0003_alter_borrow_book"),
        ("main", "0003_alter_profile_role"),
    ]

    operations = [
        migrations.DeleteModel(name="Book",),
    ]
