# Generated by Django 4.2.7 on 2023-12-04 08:59

from django.db import migrations
from django.core.management import call_command


def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "book")


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_isbn13'),
    ]

    operations = [
    migrations.RunPython(load_my_initial_data),
]