# Generated by Django 4.2.6 on 2023-10-28 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_auto_20231026_0831"),
        ("borrow_book", "0002_alter_borrow_borrow_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="book.book"
            ),
        ),
    ]
