# Generated by Django 4.2.6 on 2023-10-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrow_book", "0003_alter_borrow_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrow", name="status", field=models.BooleanField(default=True),
        ),
    ]
