# Generated by Django 4.2.6 on 2023-10-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrow_book", "0004_borrow_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
