# Generated by Django 4.2.6 on 2023-10-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_book', '0005_alter_borrow_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='status',
        ),
    ]
